use crate::watch::parse::{Artifact, Kind};

/// Build a HunterFinding JSON (camelCase, mirrors src-tauri/src/findings.rs) from
/// a watch alert. Severity is passed already-lowercased so it matches the UI.
pub fn build_watch_finding_json(
    id: &str,
    target: &str,
    title: &str,
    severity_lc: &str,
    top: i64,
    kept: &[(i64, Artifact)],
    source_url: &str,
) -> String {
    // De-duplicate by value within each bucket while preserving score order.
    let mut secrets = Vec::new();
    let mut endpoints = Vec::new();
    let mut routes = Vec::new();
    let mut flags = Vec::new();
    for (s, a) in kept {
        let line = format!("[{s}] {}", a.value);
        match a.kind {
            Kind::Secret => secrets.push(a.value.clone()),
            Kind::Endpoint => endpoints.push(line),
            Kind::Route => routes.push(line),
            Kind::Flag => flags.push(line),
        }
    }
    let mut evidence = format!("Trapline Watch — new attack surface on {target}\nSource: {source_url}\n");
    if !secrets.is_empty() {
        evidence.push_str(&format!("\nNew secrets ({}):\n{}\n", secrets.len(), secrets.join("\n")));
    }
    if !endpoints.is_empty() {
        evidence.push_str(&format!("\nNew endpoints ({}):\n{}\n", endpoints.len(), endpoints.join("\n")));
    }
    if !routes.is_empty() {
        evidence.push_str(&format!("\nNew routes ({}):\n{}\n", routes.len(), routes.join("\n")));
    }
    if !flags.is_empty() {
        evidence.push_str(&format!("\nNew flags ({}):\n{}\n", flags.len(), flags.join("\n")));
    }

    let finding = serde_json::json!({
        "id": id,
        "programName": target,
        "platform": "Watch",
        "title": title,
        "severity": severity_lc,
        "status": "draft",
        "endpoint": source_url,
        "summary": format!("Watch detected {} new artifact(s) on {} (top score {}).", kept.len(), target, top),
        "description": "",
        "steps": "",
        "evidence": evidence,
        "impact": "",
        "remediation": "",
        "cvss": "",
        "cvssScore": "",
        "notes": "Auto-generated by built-in Trapline Watch.",
        "cmdline": "trapline-watch",
    });
    serde_json::to_string(&finding).unwrap()
}

/// Persist a watch alert as a finding in the in-process store.
pub fn record_watch_finding(
    id: &str,
    target: &str,
    title: &str,
    severity_lc: &str,
    top: i64,
    kept: &[(i64, Artifact)],
    source_url: &str,
) -> Result<(), String> {
    let json = build_watch_finding_json(id, target, title, severity_lc, top, kept, source_url);
    crate::findings::save(&json)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::watch::parse::{Artifact, Kind};

    #[test]
    fn maps_kept_artifacts_to_lowercase_severity_finding() {
        let kept = vec![
            (100i64, Artifact { kind: Kind::Secret, value: "sk_live_xxx".into() }),
            (85i64, Artifact { kind: Kind::Endpoint, value: "/api/v2/admin".into() }),
        ];
        let json = build_watch_finding_json(
            "watch-1", "acme", "New attack surface on acme", "critical", 100, &kept, "https://acme.com/app.js",
        );
        let v: serde_json::Value = serde_json::from_str(&json).unwrap();
        assert_eq!(v["severity"], "critical");
        assert_eq!(v["programName"], "acme");
        assert_eq!(v["platform"], "Watch");
        assert_eq!(v["endpoint"], "https://acme.com/app.js");
        assert!(v["evidence"].as_str().unwrap().contains("/api/v2/admin"));
        assert!(v["evidence"].as_str().unwrap().contains("sk_live_xxx"));
        assert_eq!(v["cmdline"], "trapline-watch");
    }
}
