// Ported verbatim from main:src/main.js — the generateReport(f) builder that
// backed #genReportBtn (~line 1096). Same section order, labels, and
// [bracket] placeholders; only re-typed for the SvelteKit front end (Finding
// instead of a loose object literal, CVSS_DEFAULTS/owaspRef from cvss.ts).
import type { Finding } from '$lib/types';
import { CVSS_DEFAULTS, owaspRef, type Severity } from '$lib/data/cvss';

export function generateReport(f: Finding): string {
  const sev = f.severity ? f.severity.charAt(0).toUpperCase() + f.severity.slice(1) : '[Severity]';
  const d = CVSS_DEFAULTS[f.severity as Severity] || CVSS_DEFAULTS.medium;
  const cvss = f.cvss || d.vector;
  const score = f.cvssScore || d.score;
  const justification = d.justification;
  const ref = owaspRef(f.title);

  const title = f.title || '[Vulnerability type] in [endpoint] allows [action] leading to [business impact]';
  const summary = f.summary || '[2–3 sentences: What is the vulnerability, where is it, and how severe is it?]';
  const steps =
    f.steps ||
    '1. [Step]\n2. [Include exact curl command with full headers]\n3. [Observe impact — screenshot or paste response]';
  const evidence = f.evidence || '[Paste raw HTTP request/response or curl command output here]';
  const impact =
    f.impact ||
    '[An [attacker type] can [action] by [method], allowing [consequence] affecting [scope], exposing [company] to [regulatory/financial risk].]';
  const remediation = f.remediation || '[Specific technical fix — not generic advice]';
  const prog = f.programName ? 'Program: ' + f.programName + '\n' : '';

  return `${prog}TITLE: ${title}

SEVERITY: ${sev}
CVSS: ${cvss} — Score: ${score}
CVSS Justification: ${justification}

SUMMARY:
${summary}

VULNERABILITY DESCRIPTION:
[Technical explanation of the root cause. What developer assumption was wrong? Where is the missing control?]

STEPS TO REPRODUCE:
${steps}

PROOF OF CONCEPT:
\`\`\`
${evidence}
\`\`\`

IMPACT:
${impact}

REMEDIATION:
${remediation}

REFERENCES:
${ref}

---
Generated by Trapline — @foodstampplug`;
}
