<script lang="ts">
  // Deck launcher — the 📡 rail panel that starts/stops the trapline-deck
  // phone-remote (a local Node process + optional cloudflared tunnel) so the
  // user can drive Trapline from their phone, already logged in, over Wi-Fi.
  // Ported from main:index.html #deck + main:src/main.js renderDeck()/
  // deckStart()/deckStop()/deckSaveFolder()/deckDot()/copyText() (~lines
  // 706-772). Same modal-card shell as FindingsPanel.svelte/Loot.svelte/
  // Settings.svelte.
  import { deckStart, deckStop, deckStatus, deckSetFolder } from '$lib/bridge';
  import type { DeckStatus } from '$lib/types';

  let { open = $bindable(false) }: { open?: boolean } = $props();

  type DotState = 'stopped' | 'starting' | 'running';

  let status = $state<DeckStatus>({ running: false });
  let dotState = $state<DotState>('stopped');
  let folder = $state('');
  let starting = $state(false);
  let folderSaved = $state(false);
  let folderSavedTimer: ReturnType<typeof setTimeout> | undefined;
  let copied = $state<string | null>(null);
  let copiedTimer: ReturnType<typeof setTimeout> | undefined;

  const tunnelCmd = $derived(status.port ? `cloudflared tunnel --url http://localhost:${status.port}` : '');

  // Load current state whenever the panel OPENS — not on unconditional
  // mount. <Deck> is mounted once for the whole session (like Loot/
  // Settings/FindingsPanel) inside Cockpit.svelte; if this fired
  // unconditionally it would hit the Tauri bridge as soon as Cockpit
  // mounts, which throws outside a real Tauri webview and breaks
  // Cockpit.test.ts. Gating on `open` keeps the closed instance inert.
  $effect(() => {
    if (!open) return;
    void refresh();
  });

  async function refresh(): Promise<void> {
    try {
      const s = await deckStatus();
      applyStatus(s);
    } catch (e) {
      console.error(e);
    }
  }

  function applyStatus(s: DeckStatus): void {
    status = s;
    dotState = s.running ? 'running' : 'stopped';
  }

  function close(): void {
    open = false;
  }

  async function start(): Promise<void> {
    dotState = 'starting';
    starting = true;
    try {
      const s = await deckStart();
      applyStatus(s);
    } catch (e) {
      console.error(e);
      dotState = 'stopped';
    } finally {
      starting = false;
    }
  }

  async function stop(): Promise<void> {
    try {
      await deckStop();
      applyStatus({ running: false });
    } catch (e) {
      console.error(e);
      // Stop failed — resync to the real state instead of leaving the UI stale.
      await refresh();
    }
  }

  async function saveFolder(): Promise<void> {
    try {
      await deckSetFolder(folder.trim());
      folderSaved = true;
      clearTimeout(folderSavedTimer);
      folderSavedTimer = setTimeout(() => (folderSaved = false), 1500);
    } catch (e) {
      console.error(e);
    }
  }

  async function copy(text: string, label: string): Promise<void> {
    if (!text) return;
    try {
      await navigator.clipboard.writeText(text);
      copied = label;
      clearTimeout(copiedTimer);
      copiedTimer = setTimeout(() => (copied = null), 1500);
    } catch (e) {
      console.error(e);
    }
  }

  function onWindowKeydown(e: KeyboardEvent): void {
    if (open && e.key === 'Escape') {
      e.preventDefault();
      close();
    }
  }
</script>

<svelte:window onkeydown={onWindowKeydown} />

{#if open}
  <div class="overlay">
    <button type="button" class="backdrop" aria-label="Close deck" onclick={close}></button>
    <div class="modal-card" role="dialog" aria-modal="true" aria-label="Deck">
      <div class="modal-head">
        <h2>
          📡 Deck
          <span class="dot {dotState}"></span>
          <span class="status-text">{dotState === 'starting' ? 'starting…' : dotState}</span>
        </h2>
        <button type="button" class="icon-btn sm" title="Close" onclick={close}>✕</button>
      </div>
      <p class="modal-sub">
        Run the phone remote on this machine, then scan the QR to open it on your phone — already
        logged in — over your Wi-Fi.
      </p>

      <div class="deck-controls">
        {#if !status.running}
          <button type="button" class="run-btn" onclick={start} disabled={starting}>
            {starting ? 'Starting…' : 'Start Deck ▸'}
          </button>
        {:else}
          <button type="button" class="ghost-btn" onclick={stop}>Stop</button>
          {#if status.url}
            <a class="ghost-btn" href={status.url} target="_blank" rel="noreferrer">Open on this PC</a>
          {/if}
        {/if}
      </div>

      {#if status.running}
        <div class="deck-running">
          <div class="deck-qr">
            {#if status.lanUrl && status.qrSvg}
              <!-- qrSvg is trusted, generated by our Rust qrcode crate -->
              {@html status.qrSvg}
            {:else}
              <p class="qr-fallback">Couldn't detect a LAN IP — use the tunnel command below.</p>
            {/if}
          </div>

          {#if status.lanUrl}
            <div class="deck-row">
              <label for="deckLanUrl">On this Wi-Fi</label>
              <div class="deck-copy">
                <code id="deckLanUrl">{status.lanUrl}</code>
                <button type="button" class="ghost-btn sm" onclick={() => copy(status.lanUrl ?? '', 'lan')}>
                  {copied === 'lan' ? 'Copied ✓' : 'Copy'}
                </button>
              </div>
            </div>
          {/if}

          <div class="deck-row">
            <label for="deckToken">Token</label>
            <div class="deck-copy">
              <code id="deckToken">{status.token ?? ''}</code>
              <button type="button" class="ghost-btn sm" onclick={() => copy(status.token ?? '', 'token')}>
                {copied === 'token' ? 'Copied ✓' : 'Copy'}
              </button>
            </div>
          </div>

          <div class="deck-row">
            <label for="deckTunnelCmd">Off your network? Run a tunnel, then open the printed URL</label>
            <div class="deck-copy">
              <code id="deckTunnelCmd">{tunnelCmd}</code>
              <button type="button" class="ghost-btn sm" onclick={() => copy(tunnelCmd, 'tunnel')}>
                {copied === 'tunnel' ? 'Copied ✓' : 'Copy'}
              </button>
            </div>
          </div>

          <p class="deck-note">
            Same Wi-Fi? Just scan the QR. First phone connection may need Windows Firewall to allow
            <b>node.exe</b> (one-time).
          </p>
        </div>
      {/if}

      <details class="deck-adv">
        <summary>Advanced — Deck folder</summary>
        <label for="deckFolder">Path to your trapline-deck folder</label>
        <div class="deck-copy">
          <input
            id="deckFolder"
            type="text"
            spellcheck="false"
            placeholder="C:\Users\you\trapline-deck"
            bind:value={folder}
          />
          <button type="button" class="ghost-btn sm" onclick={saveFolder}>
            {folderSaved ? 'Saved ✓' : 'Save'}
          </button>
        </div>
      </details>

      <div class="modal-actions">
        <span class="spacer"></span>
        <button type="button" class="ghost-btn" onclick={close}>Close</button>
      </div>
    </div>
  </div>
{/if}

<style>
  .overlay {
    position: fixed;
    inset: 0;
    z-index: 50;
    background: rgba(0, 0, 0, 0.6);
    backdrop-filter: blur(8px);
    display: flex;
    align-items: center;
    justify-content: center;
  }
  .backdrop {
    position: absolute;
    inset: 0;
    z-index: 0;
    width: 100%;
    height: 100%;
    padding: 0;
    margin: 0;
    border: none;
    background: transparent;
    cursor: default;
  }
  .modal-card {
    position: relative;
    z-index: 1;
    width: min(92vw, 460px);
    max-height: 90vh;
    overflow-y: auto;
    background: rgba(12, 13, 16, 0.92);
    backdrop-filter: blur(28px);
    border: var(--bordw) solid var(--edge2);
    border-radius: var(--radius);
    padding: 22px;
    box-shadow: var(--shadow);
  }
  .modal-head {
    display: flex;
    align-items: center;
    gap: 8px;
    margin-bottom: 8px;
  }
  .modal-head h2 {
    margin: 0;
    display: flex;
    align-items: center;
    gap: 8px;
    font: 700 18px/1 var(--fdisp);
    color: var(--ink);
  }
  .icon-btn {
    width: 28px;
    height: 28px;
    display: grid;
    place-items: center;
    border-radius: calc(var(--radius) - 8px);
    border: var(--bordw) solid var(--edge);
    background: transparent;
    color: var(--muted);
    cursor: pointer;
    font-size: 13px;
    margin-left: auto;
    flex-shrink: 0;
  }
  .icon-btn:hover {
    color: var(--ink);
    border-color: var(--accent);
  }
  .modal-sub {
    font: 500 12px/1.5 var(--fui);
    color: var(--dim);
    margin: 0 0 14px;
  }

  .dot {
    width: 8px;
    height: 8px;
    border-radius: 50%;
    background: var(--muted);
    flex-shrink: 0;
  }
  .dot.running {
    background: var(--accent);
    box-shadow: 0 0 6px color-mix(in srgb, var(--accent) 60%, transparent);
  }
  .dot.starting {
    background: var(--accent2);
    box-shadow: 0 0 6px color-mix(in srgb, var(--accent2) 60%, transparent);
    animation: pulse 1.1s infinite;
  }
  .status-text {
    font: 600 12px/1 var(--fui);
    color: var(--muted);
  }
  @keyframes pulse {
    50% {
      opacity: 0.4;
    }
  }

  .deck-controls {
    display: flex;
    gap: 8px;
    margin-bottom: 14px;
  }

  .deck-running {
    display: flex;
    flex-direction: column;
    gap: 10px;
    margin-bottom: 6px;
  }
  .deck-qr {
    display: flex;
    justify-content: center;
    align-items: center;
    background: #fff;
    border-radius: calc(var(--radius) - 6px);
    padding: 14px;
    min-height: 60px;
  }
  .deck-qr :global(svg) {
    width: 180px;
    height: 180px;
    display: block;
  }
  .qr-fallback {
    margin: 0;
    color: #333;
    font: 500 12px/1.5 var(--fui);
    text-align: center;
    padding: 12px;
  }

  .deck-row {
    display: flex;
    flex-direction: column;
    gap: 5px;
  }
  .deck-row label {
    font: 700 11px/1.3 var(--fui);
    color: var(--muted);
    text-transform: uppercase;
    letter-spacing: 0.04em;
  }
  .deck-copy {
    display: flex;
    align-items: center;
    gap: 8px;
  }
  .deck-copy code {
    flex: 1;
    min-width: 0;
    background: rgba(0, 0, 0, 0.28);
    border: var(--bordw) solid var(--edge2);
    border-radius: calc(var(--radius) - 6px);
    color: var(--ink);
    padding: 9px 11px;
    font: 500 12px/1.3 var(--fmono);
    overflow-x: auto;
    white-space: nowrap;
  }
  .deck-copy input {
    flex: 1;
    min-width: 0;
    background: rgba(0, 0, 0, 0.28);
    border: var(--bordw) solid var(--edge2);
    border-radius: calc(var(--radius) - 6px);
    color: var(--ink);
    padding: 9px 11px;
    outline: none;
    font: 500 13px/1.4 var(--fui);
    transition: border-color 0.15s, box-shadow 0.15s;
  }
  .deck-copy input:focus {
    border-color: var(--accent);
    box-shadow: 0 0 0 3px var(--glowa);
  }

  .deck-note {
    margin: 2px 0 0;
    font: 500 11px/1.5 var(--fui);
    color: var(--dim);
  }
  .deck-note b {
    color: var(--muted);
    font-family: var(--fmono);
  }

  .deck-adv {
    margin-top: 14px;
    padding-top: 14px;
    border-top: var(--bordw) solid var(--edge);
  }
  .deck-adv summary {
    cursor: pointer;
    font: 700 11px/1 var(--fui);
    color: var(--muted);
    text-transform: uppercase;
    letter-spacing: 0.04em;
    margin-bottom: 10px;
  }
  .deck-adv summary:hover {
    color: var(--ink);
  }
  .deck-adv label {
    display: block;
    font: 600 12px/1.4 var(--fui);
    color: var(--dim);
    margin-bottom: 6px;
  }

  .modal-actions {
    display: flex;
    align-items: center;
    gap: 8px;
    margin-top: 18px;
    padding-top: 14px;
    border-top: var(--bordw) solid var(--edge);
  }
  .modal-actions .spacer {
    flex: 1;
  }
  .ghost-btn {
    background: transparent;
    border: var(--bordw) solid var(--edge2);
    color: var(--muted);
    border-radius: calc(var(--radius) - 6px);
    padding: 9px 14px;
    font: 600 13px/1 var(--fui);
    cursor: pointer;
    transition: 0.15s;
    text-decoration: none;
    display: inline-flex;
    align-items: center;
  }
  .ghost-btn:hover:not(:disabled) {
    color: var(--ink);
    border-color: var(--accent);
  }
  .ghost-btn:disabled {
    opacity: 0.45;
    cursor: not-allowed;
  }
  .ghost-btn.sm {
    padding: 7px 10px;
    font-size: 12px;
    flex-shrink: 0;
  }
  .run-btn {
    font: 700 13px/1 var(--fdisp);
    /* Dark-on-amber text — same hex Loot.svelte/Settings.svelte/
       FindingEditor.svelte already use for buttons on var(--accent); reused,
       not a new hex. */
    color: #221a06;
    background: var(--accent);
    border: none;
    border-radius: calc(var(--radius) - 6px);
    padding: 10px 16px;
    cursor: pointer;
  }
  .run-btn:hover:not(:disabled) {
    filter: brightness(1.09);
  }
  .run-btn:active:not(:disabled) {
    transform: translateY(1px);
  }
  .run-btn:disabled {
    opacity: 0.6;
    cursor: not-allowed;
  }
</style>
